WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pilot:
            type: string
            length: 255
            nullable: true
        freeSeats:
            type: integer
            nullable: true
        takeofTime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: departures

    oneToMany:
        flights:
            targetEntity: WCS\CoavBundle\Entity\Reservation
            mappedBy: flight

    manyToOne:
        plane:
            targetEntity: WCS\CoavBundle\Entity\plane_model

    manyToOne:
        arrival:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: arrivals